Update main.js
htmlacademy-javascript/2100191-kekstagram-26 pull request #2
Opened 2022-06-16 18:53 UTC by ArthurSkorzeny

2022-06-16 19:50 UTC, o-bender requested changes
```
Array.from({length: PHOTO_OBJECT_COUNT}, (sourceArrayItem, sourceArrayItemIndex) => {
    //sourceArrayItem элемент исходного массива. Т.к. ты используешь хак с {length: PHOTO_OBJECT_COUNT}. То в нём всегда будет приходить undefined
   // sourceArrayItemIndex порядковый номер элемента - вот это можешь использовать как id
})
```

2022-06-16 19:50 UTC, o-bender commented on js/main.js
> +    id: getRandomPositiveInteger('0','600'),
Кавычки не нужны. Ты сейчас передаёшь в функцию строки. Строки разбираются и превращаются в цифры. Это как минимум лишние операции.

2022-06-16 19:50 UTC, o-bender commented on js/main.js
> +    avatar: 'img/avatar-' + getRandomPositiveInteger('1','6') + '.svg',
1. Лишние кавычки у цифр
2. Используй обратные кавычки и синтаксис шаблонных строк.

2022-06-16 19:50 UTC, o-bender commented on js/main.js
> +const commentObjects = Array.from({length: 1}, createCommentObject);
Это должно быть функцией `createComments`

2022-06-16 19:50 UTC, o-bender commented on js/main.js
> + const photoObjects = Array.from({length: PHOTO_OBJECT_COUNT}, createPhotoObject);
Это должно быть функцией `createPhotos`

2022-06-17 06:14 UTC, o-bender requested changes

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +const commentObjects = () =>{
В именах функций должен быть глагол. Назови как-нибудь вроде createComments

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +const photoObjects = () =>{
В именах функций должен быть глагол. Назови как-нибудь вроде createPhotos

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +    avatar: 'img/avatar-' + getRandomPositiveInteger(1, 6) + '.svg',
Используй обратные кавычки 
```
`img/avatar-${getRandomPositiveInteger(1, 6)}.svg`
```

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +    url: getRandomPositiveInteger(1, 25),
Тут явно забыл что-то. URL не может быть просто случайной цифрой.

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +  let comment = Array.from({length: 1}, createCommentObject);
Пусть генерится штук по 5 комментов. Это в следующих заданиях пригодится.

2022-06-17 06:14 UTC, o-bender commented on js/main.js
> +    id: getRandomPositiveInteger(1, 25),
Так они по-прежнему не будут уникальными. 
```
const createPhotoObject = (id) => {
    return {
         id,
         url: и т.д.
    };
}

const createPhotos = () => Array.from({length: PHOTO_OBJECT_COUNT}, (_, id) => createPhotoObject(id))
```

С id для комментариев тоже самое надо сделать.

2022-06-17 07:43 UTC, ArthurSkorzeny commented
Как я не пытаюсь, я не могу решить задачу с id и url , пытался как-то с вашей подсказкой работать, у меня ничего не получается и я не могу найти что либо в интернете. Возможно это очень просто, но я третий день не могу это сделать

2022-06-17 07:45 UTC, ArthurSkorzeny commented
Я пробовал выводить данные массива через цикл, но цикл начинается заново, при каждом запуске функции, есть ли какой то способ продолжать цикл вместе с основной функцией( 25 раз) ?

2022-06-17 18:35 UTC, o-bender commented on js/main.js
> +    url: 'photos/'+id+'.jpg',
используй обратные кавычки. как в avatar.

2022-06-17 18:35 UTC, o-bender commented on js/main.js
> +const createPhotos = () => Array.from({length: PHOTO_OBJECT_COUNT}, (_, id) => createPhotoObject(id))
вместо id++ давай лучше так:
```
const createPhotos = () => Array.from({length: PHOTO_OBJECT_COUNT}, (_, id) => createPhotoObject(id + 1))
```
И в комментариях тоже самое.

2022-06-17 18:35 UTC, o-bender commented on js/main.js
> +const createComment = () => Array.from({length: 5}, (_, id) => createCommentObject(id))
Лучше во множественном числе createComments

2022-06-18 10:27 UTC, merged