Module7 task1
htmlacademy-javascript/2100191-kekstagram-26 pull request #5
Opened 2022-06-23 13:04 UTC by ArthurSkorzeny

2022-06-23 13:14 UTC, ArthurSkorzeny commented
Я не могу быть уверен в работе, потому что chrome не хотел подключать js файл и на странице показывался чистый html.

2022-06-23 15:34 UTC, o-bender requested changes
Ещё немного про main.js и импорты с экспортами.
1. main.js это точка входа в твоё приложение. т.е. от этого файла начинается выполнение твоей программы в нём же оно заканчивается.
2. В main.js можно импортировать но нельзя из него экспортировать. Физически это возможно сделать, но так делать не надо.
3. Если к примеру два модуля импортируют друг друга. Модуль А импортирует функцию b из модуля B, а B из A функцию a, то стоит задуматься либо слиянии этих модулей в один, либо частичном переносе функций из одного модуля в другой. Такие импорты называются циклическими.

Перед пушем:
1. Запускай `npm run lint`
2. Проверяй, что код работает. Если не работает, смотри ошибки в консоли браузера. Если в консоли чисто и идей нет, то пиши в телеграмм. Пиши, что ошибок в консоли нет, а почему не рисуется в браузере не понимаешь.=( В реальной работе работоспособность твоего кода это твоя ответственность. Код конечно проходит ревью тимлидом или командой, но ответственность за него нести будешь ты. Даже не смотря на то что ты джуниор.=)

2022-06-23 15:34 UTC, o-bender commented on js/random_user_image.js
> +const photoObj = createPhotos();
Это должно переехать в main.js

2022-06-23 15:34 UTC, o-bender commented on js/random_user_image.js
> +const similarListFragment = document.createDocumentFragment();
Отсюда и до конца модуля должно стать функцией `const renderPhotos = (photos) =>`. И вызываться в main.js. Это добавит гибкости, управляемости и предсказуемости. И хоть на js1 и не проходят тестирование (а стоило бы), но функцию можно протестировать в отрыве от остального кода. А когда это просто набор инструкций в модуле, то это протестировать реально, но сложно.

2022-06-23 15:34 UTC, o-bender commented on js/random_user_image.js
> +  picture.querySelector('.picture__comments').textContent = comments;
Перед пушем запускай `npm run lint`. Тут жалуется на лишние пробелы в конце строки.

2022-06-23 15:34 UTC, o-bender commented on js/random_user_image.js
> +  picture.querySelector('.picture__comments').textContent = comments;
picture__comments это счётчик комментариев. Мне кажется ты не запускал этот код.

2022-06-23 15:34 UTC, o-bender commented on js/random_user_image.js
> +  picture.querySelector('.picture__img').setAttribute('src', url);
Мб лучше просто `picture.querySelector('.picture__img').src = url`? "Минус" такого решения, что атрибут не будет в разметке отображаться.

2022-06-24 09:34 UTC, ArthurSkorzeny commented
Запустил, проверил - все работает.Наверное с количеством комментариев нужно было поступить по другому?

2022-06-24 14:35 UTC, o-bender commented on js/random_user_image.js
> +  picture.querySelector('.picture__comments').textContent = getRandomPositiveInteger(10, 100);
У тебя уже есть комментарии, нужно выводить их кол-во. Т.е. 
```
picture.querySelector('.picture__comments').textContent = comments.length;
```

2022-06-24 14:41 UTC, ArthurSkorzeny commented
Я подозревал, что нужно выводить длину, но как-то не сориентировался. Спасибо, буду знать

2022-06-24 14:42 UTC, ArthurSkorzeny commented
По тем двум комментариям сейчас додумаю

2022-06-24 17:01 UTC, merged