Module7 task2
htmlacademy-javascript/2100191-kekstagram-26 pull request #6
Opened 2022-06-26 12:23 UTC by ArthurSkorzeny

2022-06-27 16:24 UTC, ArthurSkorzeny commented
Тут нет последних пунктов задания и может showBigPicture написана не правильно, но я это быстро исправлю, когда пойму , как передавать обьект

2022-06-27 18:29 UTC, o-bender requested changes

2022-06-27 18:29 UTC, o-bender commented on js/big-picture.js
> +function showBigPicture(photo) {
1. Давай пользоваться стрелочными функциями
2. Давай-как мы эту функцию упростим:)
Для начала вынесем makeComment, просто потому что нам ни что не мешает это сделать.
```
const makeComment = ({avatar, name, message}) => {
      const socialComment = commentTemplate.cloneNode(true);
      socialComment.querySelector('social_picture').setAttribute('src', avatar);
      socialComment.querySelector('social_picture').setAttribute('alt', name);
      socialComment.querySelector('social__text').textContent = message;
      return socialComment;
};

function showBigPicture(photo) {
  return function(url, likes, comments, description) {
    fullScreen.removeClass('hidden');
    fullScreen.querySelector('.big-picture__img').firstElementChild.setAttribute('src', url);
    fullScreen.querySelector('.likes-count').textContent = likes;
    fullScreen.querySelector('.comments-count').textContent = comments.lenght;
    fullScreen.querySelector('.social__caption').textContent = description;

    const similarListFragment = document.createDocumentFragment();
    comments.forEach((comment) => similarListFragment.appendChild(makeComment(comment)));
    commentList.appendChild(similarListFragment);
  };
}
```

Теперь уберём лишнее:
```
const showBigPicture = ({url, likes, comments, description}) => {
    fullScreen.querySelector('.big-picture__img').firstElementChild.setAttribute('src', url);
    fullScreen.querySelector('.likes-count').textContent = likes;
    fullScreen.querySelector('.comments-count').textContent = comments.lenght;
    fullScreen.querySelector('.social__caption').textContent = description;

    const similarListFragment = document.createDocumentFragment();
    comments.forEach((comment) => similarListFragment.appendChild(makeComment(comment)));
    commentList.appendChild(similarListFragment);

    // Перенесём эту строку сюда, что бы все операции производить над невидимыми элементами 
    // и не заставлять браузер перерисовывать наши элементы на каждое изменение
    fullScreen.removeClass('hidden'); 
};

Ок. Получили две простые функции. Осталось их применить:
```
const makePhotoElement = (photo) => {
  const {url, likes, comments} = photo;
  const pictureElement = templateFragment.cloneNode(true);
  pictureElement.querySelector('.picture__img').setAttribute('src', url);
  pictureElement.querySelector('.picture__likes').textContent = likes;
  pictureElement.querySelector('.picture__comments').textContent = comments.length;

  // Создадим анонимную функцию и вместе с ней замыкание
  pictureElement.addEventListener('click', () => showBigPicture(photo));
  return picture;
};
```

И в качестве бонуса, такую конструкцию:
```
    const similarListFragment = document.createDocumentFragment();
    comments.forEach((comment) => similarListFragment.appendChild(makeComment(comment)));
    commentList.appendChild(similarListFragment);
```
можно заменить на:
```
    commentList.append(
        comments.map(
              makeComment(comment)
        )
   );
```
Я написал всё в отдельных строках, просто что бы проще было прочесть:)

2022-06-27 20:52 UTC, ArthurSkorzeny commented
Вообщем все читается, но есть две ошибки:
Uncaught ReferenceError: comment is not defined
    at showBigPicture (big-picture.js:22:19)
    at HTMLAnchorElement.<anonymous> (random_user_image.js:12:50)

Одна ругается на comment , при такой записи он выделяется, как is not defined, а при другой записи целых 2 ошибки.

А вторая ругается на вызов функции?Не нашел решения такой ошибки, только описание такого явления

2022-06-27 20:59 UTC, ArthurSkorzeny commented on js/big-picture.js
> +function showBigPicture(photo) {
Вынесение makeComment будто ходило в моей голове, потому-что смотрел на него и думал,что оно не к месту там, но ничего не сделал.
В первый раз увидел анонимную функцию, как посмотрел, она в основном в замыканиях и используются.
Про такое получение photo я даже не подумал, но как в него попадет description?
Бонус интересный получился, на вид простой, а при понимании сложный.

2022-06-28 15:54 UTC, o-bender requested changes

2022-06-28 15:54 UTC, o-bender commented on js/big-picture.js
> +      makeComment(comment)
Сорян, обманул немного:
```
commentList.append(...comments.map(makeComment))
```

2022-06-29 08:17 UTC, o-bender approved these changes

2022-06-29 08:17 UTC, o-bender commented on js/bg_close_button.js
> +document.addEventListener('keydown', (e) => {
1. содержимое `closeButton.addEventListener('click'` полностью дублируется в этом обработчике.
2. `document.addEventListener('keydown'` этот слушатель необходимо устанавливать в момент открытия модального окна. И в момент закрытия удалять.

2022-06-29 08:17 UTC, o-bender commented on js/bg_close_button.js
> +    fullScreen.querySelector('.social__comment-count').removeClass('hidden');
Этот и следующий hidden в общем-то лишние. Т.к. ты скрываешь модальное окно и счётчик и кнопку уже ни кто не увидит:) И их сокрытие это временно, скоро их скрывать не надо будет.

2022-06-29 08:17 UTC, o-bender commented on js/bg_close_button.js
> +    fullScreen.reset();
А что ты ресетишь?

2022-06-29 08:17 UTC, o-bender commented on js/bg_close_button.js
> +closeButton.addEventListener('click', ()=> {
На нашем масштабе это не критично, но всё же это сайд эффект. И я бы поместил этот вызов в функцию и вызывал бы её в main.js.

2022-06-29 08:17 UTC, merged