Правда или действие (часть 2)
htmlacademy-javascript/2100191-kekstagram-26 pull request #8
Opened 2022-07-07 14:56 UTC by ArthurSkorzeny

---
:mortar_board: [Правда или действие (часть 2)](https://up.htmlacademy.ru/javascript/26/user/2100191/tasks/16)

:boom: https://htmlacademy-javascript.github.io/2100191-kekstagram-26/8/

2022-07-08 17:18 UTC, o-bender requested changes
main.js самая первая строка ведёт в неизвестность)

2022-07-08 17:18 UTC, o-bender commented on js/big-picture.js
>      fullScreen.querySelector('.social__comment-count').removeClass('hidden');
removeClass - такого метода несуществует

2022-07-08 17:18 UTC, o-bender commented on js/buttons.js
> +  pictureCancel.addEventListener('click', () => {
часть этой функции дублирует код из hideBigPictureButton. Я бы сделал так:
1. в hideBigPictureButton убрал бы ветвление с Escape.
2. создал бы ещё одну функцию onCloseBigPicture - и вот в неё добавил бы ветвление и 
```
if (e.key === 'Escape') {
    hideBigPictureButton();
}
```
3. И соответственно в этой функции вместо дублирования кода вызывал бы hideBigPictureButton

2022-07-08 17:18 UTC, o-bender commented on js/big-picture.js
> +  for(let i = 0; i <= 4; i++){
Тут что-то не то. Почему первые 5 всегда видимы? А остальные как же?
![image](https://user-images.githubusercontent.com/6534704/178038618-8b26284b-4fd8-4564-ae62-1119c82ded1f.png)

2022-07-08 17:18 UTC, o-bender commented on js/big-picture.js
> +  //fullScreen.querySelector('.comments-count').textContent = comments.lenght;
length

2022-07-08 17:18 UTC, o-bender commented on js/buttons.js
> +    uplFile.innerHTML = ' ';
Не надо так. Для этого у формы (в этом случае .img-upload__form) есть метод reset.

2022-07-08 17:18 UTC, o-bender commented on js/buttons.js
> +    if (startCommentsLenght === maxComments) {
лучше всё же >=

2022-07-08 17:18 UTC, o-bender commented on js/buttons.js
> +    shownCommentsCount.innerHTML = `${startCommentsLenght} из ${maxComments} комментариев`;
Зачем это тут?

2022-07-08 17:18 UTC, o-bender commented on js/big-picture.js
> +  //fullScreen.querySelector('.comments-count').textContent = comments.lenght;
А вот тут 
```
shownCommentsCount.textContent = `${startCommentsLenght} из ${maxComments} комментариев`;
```
ты затираешь тобой созданный элемент `.comments-count` и соответственно получаешь ошибку при доступе к нему.

2022-07-08 17:18 UTC, o-bender commented on js/buttons.js
> +let startCommentsLenght = 5;
startCommentsLength

2022-07-08 20:05 UTC, ArthurSkorzeny commented
Буду надеяться, что в этот раз, у вас все сработает как надо, а то мне будет грустно, если я по невнимательности опять что-то неправильно перенес

2022-07-09 07:42 UTC, o-bender requested changes
При открытии картинки, видна кнопка загрузить ещё и при нажатии на неё получается вот такое вот:
![image](https://user-images.githubusercontent.com/6534704/178096455-ff4b9d24-739f-4863-9ed6-75a21ee7980c.png)
Сделай так что бы комментариев у картинок было разное кол-во. У одной 1, у другой 16.
![image](https://user-images.githubusercontent.com/6534704/178096720-b5a73fc6-2ef7-48e3-878e-0985f75e5690.png)


Окно загрузки картинки не закрывается по нажатию на Escape.

2022-07-09 10:50 UTC, o-bender approved these changes

2022-07-09 10:50 UTC, o-bender commented on js/big-picture.js
> +  if (comList.length >= 5) {
Эта пятёрка часто встречается) Так что её стоит вынести в константу.

2022-07-09 10:50 UTC, o-bender commented on js/big-picture.js
> +    newText.textContent = ' 5  из ';
И опять пятёрка

2022-07-09 10:50 UTC, o-bender commented on js/big-picture.js
> +    for(let i = 0; i <= 4; i++){
И всё же давай уберём этот цикл, тут и 4 захардкоженная и сам по себе цикл for который по критериям стоит заменять на forEach.
Мб, что-то вроде: `comList.slice(0, 5).forEach((element) => element.classList.remove('hidden'))`?

2022-07-09 10:50 UTC, o-bender commented on js/big-picture.js
> +    for(let i = 0; i <= 4; i++){
Ну пятёрка)

2022-07-09 10:50 UTC, o-bender commented on js/buttons.js
> +      const array = Array.from(document.querySelectorAll('.social__comment'));
Т.к. ты сразу все комментарии добавляешь в разметку, то тут можно было бы использовать такой селектор:
```
const array = Array.from(document.querySelectorAll('.social__comment.hidden'));
```
И тогда танцы с startCommentsLength просто стали бы не нужны.
Но это я так, просто как вариант.

2022-07-09 10:50 UTC, merged